# Generated by Django 3.1.1 on 2020-09-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='year',
            field=models.CharField(default=2011, max_length=100),
            preserve_default=False,
        ),
    ]
